# GitHub Action para generar un gráfico de contribuciones con una serpiente comiéndose tus contribuciones.

name: Generate Snake

# Controla cuándo se ejecutará la acción. Esta acción se ejecuta cada 6 horas.

on:
  schedule:
    # cada 6 horas
    - cron: "0 */6 * * *"

  # Este comando permite ejecutar la Acción automáticamente desde la pestaña Acciones.
  workflow_dispatch:

# La secuencia de ejecuciones en este flujo de trabajo:
jobs:
  # Este flujo de trabajo contiene un solo trabajo llamado "build"
  build:
    # El tipo de corredor en el que se ejecutará el trabajo
    runs-on: ubuntu-latest

    # Los pasos representan una secuencia de tareas que se ejecutarán como parte del trabajo
    steps:

    # Comprueba el repositorio bajo $GITHUB_WORKSHOP, para que tu trabajo pueda acceder a él
      - uses: actions/checkout@v3

    # Genera la serpiente  
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
